# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicTaste' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for MusicTaste
  pod 'Parse'
  pod 'Parse/UI'
  pod 'GMImagePicker'
  pod 'AFNetworking'
  pod 'BDBOAuth1Manager'

  target 'MusicTasteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MusicTasteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
